# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cbga_proportional <- function(f, lower, upper, n_lifetimes, n_population, n_chromosomes, pi_mutation, pi_recombination, s_age, s_mutation, trace) {
    .Call('_CBGA_cbga_proportional', PACKAGE = 'CBGA', f, lower, upper, n_lifetimes, n_population, n_chromosomes, pi_mutation, pi_recombination, s_age, s_mutation, trace)
}

